### ISSUE TITLE
Error running agents

### ISSUE THREAD

**Issue by Hema2-official** [openai/Video-Pre-Training#21]
Hi!

I've got trough the painful installation process and freshly downloaded a model and a weight, when this happened:

```
C:\AI-stuff\minerl\Video-Pre-Training-main>python run_agent.py --model model/foundation-model-1x.model --weights model/foundation-model-1x.weights
C:\Users\meh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gym\logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
C:\AI-stuff\minerl\Video-Pre-Training-main\lib\torch_util.py:44: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  DEFAULT_DEVICE = th.device(type=default_device_type())
Traceback (most recent call last):
  File "C:\AI-stuff\minerl\Video-Pre-Training-main\run_agent.py", line 35, in <module>
    main(args.model, args.weights)
  File "C:\AI-stuff\minerl\Video-Pre-Training-main\run_agent.py", line 9, in main
    env = Survival(**ENV_KWARGS).make()
  File "C:\Users\meh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\minerl\herobraine\env_specs\survival_specs.py", line 44, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\meh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\minerl\herobraine\env_specs\simple_embodiment.py", line 34, in __init__
    super().__init__(name, *args, **kwargs)
TypeError: EnvSpec.__init__() got an unexpected keyword argument 'fov_range'
```

I think it's not my fault 😢

Anyway, one thing I did while installing, maybe this is the problem:
Once, in _requirements.txt_, a wise line said `torch=1.9.0`.
But _pip_, being salty for something, stated this:
```
ERROR: Could not find a version that satisfies the requirement torch==1.9.0 (from versions: 1.11.0, 1.12.0, 1.12.1)
ERROR: No matching distribution found for torch==1.9.0
```

This was quite unfriendly from him.
So I swapped the version to `1.11.0`.
It installed successfully, but i quickly encountered the "_unexpected keyword argument 'fov_range'_" problem.
Rinse, repeat with versions `1.12.0` and `1.12.1`.
The problem is still unsolved, currently, `1.12.1` is installed.

Maybe I'm just not noticing something there...
Any help would be greatly appreciated!

**Comment by Miffyli** [comment]
Hey! Sorry for the long delay! Been vacationing.

Something seems to be bit off in your code: it should be creating `HumanSurvival` env, not `Survival`. See this line of code: https://github.com/openai/Video-Pre-Training/blob/main/run_agent.py#L9 . Try pulling a fresh copy of the repo and try again. Newer PyTorch versions should still work.

**Comment by Hema2-official** [comment]
Oh yeah, sorry, I forgot to mention. There was NO `HumanSurvival` class, so I went to look for a similar class and only found `Survival`... Yeah, so then the main problem is that the class is non existent in my installation... How is that possible? 😢

**Comment by Hema2-official** [comment]
Original error (stock experience):
```C:\AI-stuff\minerl\Video-Pre-Training-main>python run_agent.py --model model\foundation-model-1x.model --weights model\foundation-model-1x.weights
C:\Users\meh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gym\logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Traceback (most recent call last):
  File "C:\AI-stuff\minerl\Video-Pre-Training-main\run_agent.py", line 4, in <module>
    from minerl.herobraine.env_specs.human_survival_specs import HumanSurvival
ModuleNotFoundError: No module named 'minerl.herobraine.env_specs.human_survival_specs'```

**Comment by Miffyli** [comment]
Ah, this might be because of wrong version of MineRL. Check the installation instructions [here](https://github.com/minerllabs/minerl) for the right version of MineRL (v1.0.x, not v0.4.x).

**Comment by bbsxjy** [comment]
Hi @Hema2-official, Try rolling back your python from 3.10 to 3.9 and it will resolve this issue.
Thanks.

**Comment by Hema2-official** [comment]
Sorry for the delay, rolling back solved my problem.
Thank you!
