### ISSUE TITLE
How can I make BASALT env in VPT

### ISSUE THREAD

**Issue by Zhoues** [openai/Video-Pre-Training#37]
In the repository of VPT, I found that the way to create an environment is as follows:
```python
env = HumanSurvival(**ENV_KWARGS).make()
```
**How do I create an environment like 'MineRLBasaltBuildVillageHouse-v0' in VPT?**

---
# [Update 1]

I have taken the following two approaches:
## 1. I added a name parameter control in HumanSurvival
```python
ENV_KWARGS["name"] = "MineRLBasaltBuildVillageHouse-v0"
env = HumanSurvival(**ENV_KWARGS).make()
```
or
```python
env = HumanSurvival(name="MineRLBasaltBuildVillageHouse-v0", **ENV_KWARGS).make()
```
but it didn't have any effect; the environment remained the same as at the beginning.

## 2. I replaced HumanSurvival with the creation method provided by gym
```python
env = gym.make("MineRLBasaltMakeWaterfall-v0")
```
but when executing agent actions, the following error occurred:
```python
File "/opt/conda/envs/minerl/lib/python3.10/site-packages/gym/wrappers/time_limit.py", line 18, in step                                                                         
    observation, reward, done, info = self.env.step(action)                              
File "/opt/conda/envs/minerl/lib/python3.10/site-packages/minerl/herobraine/env_specs/basalt_specs.py", line 108, in step
    done = done or bool(action["ESC"])
KeyError: 'ESC'
```

---
# [Update 2]
I just used the second method mentioned above and manually added the value ["ESC"], and it can run normally now.

```python
env = gym.make("MineRLBasaltBuildVillageHouse-v0")
```

However, when I use `gym` to make env, the `obs` from `env.step` do not have many keys like 'location_stats' and 'inventory'. How can I get these information from env if I use `gym` but not `HumanSurvival` ?

**Comment by Miffyli** [comment]
Heya, good thing you figured it out :). 

To answer your final question: you'd have to update the environment code to provide additional information like the ones you mentioned from BASALT environments. Those were removed on purpose for the BASALT competition as the idea was to make an agent that only uses the provided info.

**Comment by Miffyli** [comment]
Heya, good thing you figured it out :). 

To answer your final question: you'd have to update the environment code to provide additional information like the ones you mentioned from BASALT environments. Those were removed on purpose for the BASALT competition as the idea was to make an agent that only uses the provided info.

**Comment by Zhoues** [comment]
> Heya, good thing you figured it out :).
> 
> To answer your final question: you'd have to update the environment code to provide additional information like the ones you mentioned from BASALT environments. Those were removed on purpose for the BASALT competition as the idea was to make an agent that only uses the provided info.

Thank you very much \\(●°u°●)/​ !
I have modified the observation space which is equal to `HumanSurvival`, and now I can get these information mentioned above.
