### ISSUE TITLE
IDM Code

### ISSUE THREAD

**Issue by kevinzakka** [openai/Video-Pre-Training#4]
Thanks so much for making the code available, it's super readable! I don't think I see the inverse dynamics model, are y'all planning on releasing that as well?

**Comment by Miffyli** [comment]
Thanks for the kind words! It is not all there is but hope it is a good starter :)

@brandonhoughton Do you think we could do this at some point (share IDM model)? I expect the process to be much smoother after this one.

**Comment by kevinzakka** [comment]
Appreciate the fast response! Thanks @brandonhoughton and @Miffyli!

**Comment by brandonhoughton** [comment]
Looking more likely - I'll close this when IDM code is public but no timeline yet

**Comment by Miffyli** [comment]
@kevinzakka The IDM code has now been added :)
