### ISSUE TITLE
Cannot download x3 or x1 models

### ISSUE THREAD

**Issue by NilaierMusic** [openai/Video-Pre-Training#5]
Models x3 and x1 cannot be downloaded by using these links:
https://openaipublic.blob.core.windows.net/minecraft-rl/models/1x.model
https://openaipublic.blob.core.windows.net/minecraft-rl/models/3x.model
![kna8wBuOf9](https://user-images.githubusercontent.com/86863646/175405744-bf6d8fac-3cce-4232-8829-9a4e4e75093c.png)

**Comment by Miffyli** [comment]
Hey, thanks for reporting this! They should be fixed now :)
