### ISSUE TITLE
Roadmap to improve

### ISSUE THREAD

**Issue by tanersekmen** [openai/Video-Pre-Training#6]
Thank you making it public, It looks amazing! Do you have any plans to improve your model?

**Comment by Miffyli** [comment]
Hey! I can not speak for the research team, but as far as I am personally aware, there are no plans to improve the models in near future.

**Comment by tanersekmen** [comment]
Thanks so much the fast response!

**Comment by brandonhoughton** [comment]
If you'd like them to improve I suggest taking part in https://www.aicrowd.com/challenges/neurips-2022-minerl-basalt-competition ! =D 
Closing for now, but thanks for asking!
