### ISSUE TITLE
BUG/Error

### ISSUE THREAD

**Issue by Dabaski** [openai/Video-Pre-Training#8]
![image](https://user-images.githubusercontent.com/55905152/175791310-c91b5774-4a2a-44ae-b349-4ebd21839e25.png)

I don't know how exactly to explain this other than something messed up somewhere.
Using Python 3.10.5 and pip 22.0.4
Tried installing to 3 machines, all coming back with this error

**Comment by Miffyli** [comment]
Hey, please open MineRL-related issues in MineRL repo, or ask on our Discord channel for help (links in MineRL repo).

Closing this issue, but double-check that you have `bash` command available (you may have to install WSL 2).
